name: zavadovskaya_client_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  video_player: ^2.9.2
  equatable: ^2.0.3
  http: ^1.2.2
  webview_flutter: ^4.10.0
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
  visibility_detector: ^0.4.0+2
  mask_text_input_formatter: ^2.9.0
  cached_network_image: ^3.4.1
  chewie: ^1.11.3
  shared_preferences: ^2.5.3
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png
